#
# AWS ECS deploy
#

on:
  workflow_dispatch

name: Deploy BACKEND to Amazon ECS

jobs:

  backend-deploy:
    name: Backend deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout BACKEND master
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push BACKEND image to Amazon ECR
      working-directory: backend
      id: build-backend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: const-sw
        IMAGE_TAG: ${{ github.sha }}-backend
      run: |
        docker build -f docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Fill in the new BACKEND image ID in the Amazon ECS task definition
      id: task-def-backend
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: backend/aws-task-definition.json
        container-name: api-alunos
        image: ${{ steps.build-backend.outputs.image }}

    - name: Deploy Amazon ECS BACKEND task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def-backend.outputs.task-definition }}
        service: api-alunos-service
        cluster: const-sw
        wait-for-service-stability: true
